export default {
  // FROM STORE
  STORE_CHANGED: 'STORE_CHANGED',

  // TO STORE
  SET_GLOBAL_LOADING: 'SET_GLOBAL_LOADING',

  SET_INCREMENT_ADD: 'SET_INCREMENT_ADD',
  SET_INCREMENT_SUBTRACT: 'SET_INCREMENT_SUBTRACT'
}
